"use client";
import {useEffect,useState} from "react";
import {useI18n} from "../i18n/client";
import "./fleet-operations.css";
type Screen={id:string;name:string;building:string;department:string;content_visibility:string;advertising_opt_in:boolean;reserved_seconds:number;restricted_categories:string[];fleet_version:number};
type Row=Record<string,any>;
type Snapshot={operators:Row[];screens:Screen[];media:Row[];announcements:Row[];audit:Row[];alertDelivery:Row[];staleMs:number;owner:boolean};
export default function FleetOperations(){
 const {locale,t}=useI18n();const [data,setData]=useState<Snapshot|null>(null);const [selected,setSelected]=useState<string[]>([]);const [filter,setFilter]=useState("");const [error,setError]=useState("");const [results,setResults]=useState<Row[]>([]);const [busy,setBusy]=useState(false);
 const [policy,setPolicy]=useState({building:"",department:"",visibility:"public",advertisingOptIn:false,reservedSeconds:0,restrictedCategories:""});
 const [mediaId,setMediaId]=useState("");const [starts,setStarts]=useState("");const [ends,setEnds]=useState("");const [name,setName]=useState("");const [operatorId,setOperatorId]=useState("");
 async function load(signal?:AbortSignal){try{const r=await fetch("/api/institution/fleet",{signal});if(r.status===404)return "unavailable";if(!r.ok){setError(t("Fleet could not be loaded."));return;}setData(await r.json());}catch{if(!signal?.aborted)setError(t("Fleet could not be loaded."));}}
 // A 404 means fleet operations are switched off. Polling on logged a 404 every 15 seconds for as long as the view stayed open.
 useEffect(()=>{const controller=new AbortController();let interval:ReturnType<typeof setInterval>|undefined;const poll=async()=>{if(await load(controller.signal)==="unavailable")clearInterval(interval);};void poll();interval=setInterval(()=>void poll(),15000);return()=>{controller.abort();clearInterval(interval);};},[]);
 async function post(body:Row){if(busy)return;setBusy(true);setError("");try{const r=await fetch("/api/institution/fleet",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const payload=await r.json();if(!r.ok)setError(t(payload.error));else setResults(payload.results??[{id:payload.id??operatorId,ok:true}]);await load();}catch{setError(t("Result uncertain. Refresh before retrying; your input is preserved."));}finally{setBusy(false);}}
 function targets(){return data?.screens.filter(s=>selected.includes(s.id)).map(s=>({id:s.id,version:s.fleet_version}))??[];}
 function schedule(){if(!starts||!ends||!Number.isFinite(Date.parse(starts))||Date.parse(ends)<=Date.parse(starts)){setError(t("Choose a valid content start and end time"));return;}void post({action:"schedule",targets:targets(),mediaId,startsAt:new Date(starts).toISOString(),endsAt:new Date(ends).toISOString()});}
 if(!data)return error?<p role="alert">{error}</p>:null;
 const visible=data.screens.filter(s=>`${s.building} ${s.department} ${s.name}`.toLowerCase().includes(filter.toLowerCase()));
 return <section className="panel fleet-operations" aria-label={t("Fleet operations")}><h2>{t("Fleet operations")}</h2><p>{t("Select explicit screens. Each result is reported separately.")}</p>
 <label>{t("Filter building or department")}<input value={filter} onChange={e=>setFilter(e.target.value)}/></label><button type="button" onClick={()=>setSelected(visible.map(s=>s.id))}>{t("Select filtered screens")}</button><button type="button" onClick={()=>setSelected([])}>{t("Clear selection")}</button><button type="button" onClick={()=>void load()}>{t("Refresh")}</button>
 <fieldset><legend>{t("Screen scope")}: {selected.length}</legend><div className="fleet-screen-list">{visible.map(s=><label key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>{setSelected(current=>e.target.checked?[...current,s.id]:current.filter(id=>id!==s.id));if(e.target.checked)setPolicy({building:s.building,department:s.department,visibility:s.content_visibility,advertisingOptIn:s.advertising_opt_in,reservedSeconds:s.reserved_seconds,restrictedCategories:s.restricted_categories.join(", ")});}}/><span><strong>{s.name}</strong><small>{s.building} / {s.department} · {t(s.content_visibility)} · {t(s.advertising_opt_in?"Open to advertising":"Institution use only")}</small></span></label>)}</div></fieldset>
 {data.owner?<form noValidate onSubmit={e=>{e.preventDefault();void post({action:"settings",targets:targets(),...policy,restrictedCategories:policy.restrictedCategories.split(",").map(s=>s.trim()).filter(Boolean)});}}><h3>{t("Owner screen policy")}</h3><div className="fleet-form-grid"><label>{t("Building")}<input value={policy.building} onChange={e=>setPolicy({...policy,building:e.target.value})}/></label><label>{t("Department")}<input value={policy.department} onChange={e=>setPolicy({...policy,department:e.target.value})}/></label><label>{t("Content visibility")}<select value={policy.visibility} onChange={e=>setPolicy({...policy,visibility:e.target.value})}><option value="public">{t("Public")}</option><option value="private">{t("Private player only")}</option></select></label><label>{t("Reserved institutional seconds per loop")}<input type="number" min="0" value={policy.reservedSeconds} onChange={e=>setPolicy({...policy,reservedSeconds:Number(e.target.value)})}/></label><label>{t("Restricted categories, comma separated")}<input value={policy.restrictedCategories} onChange={e=>setPolicy({...policy,restrictedCategories:e.target.value})}/></label><label className="fleet-checkbox"><input type="checkbox" checked={policy.advertisingOptIn} onChange={e=>setPolicy({...policy,advertisingOptIn:e.target.checked})}/>{t("Open to private-sector advertising")}</label></div><p>{t("Advertising exclusion does not make content private. Private content requires an empty screen and an authenticated player.")}</p><button className="primary-button" disabled={busy||!selected.length} type="submit">{t("Save selected screen policy")}</button><button type="button" disabled={busy||!selected.length} onClick={()=>void post({action:"publish",targets:targets()})}>{t("Publish selected screens")}</button><button type="button" disabled={busy||!selected.length} onClick={()=>void post({action:"unpublish",targets:targets()})}>{t("Unpublish selected screens")}</button></form>:null}
 <form noValidate onSubmit={e=>{e.preventDefault();schedule();}}><h3>{t("Reusable announcements and scheduling")}</h3><div className="fleet-form-grid"><label>{t("Source announcement media")}<select value={mediaId} onChange={e=>setMediaId(e.target.value)}><option value="">{t("Choose media")}</option>{data.media.map(m=><option key={m.id} value={m.id}>{m.title} · {m.inventory_id} · {t(m.approval_status)}</option>)}</select></label><label>{t("Saved announcement")}<select value="" onChange={e=>setMediaId(e.target.value)}><option value="">{t("Choose saved announcement")}</option>{data.announcements.map(a=><option key={a.id} value={a.media_id}>{a.name}</option>)}</select></label><label>{t("Content starts")}<input type="datetime-local" value={starts} onChange={e=>setStarts(e.target.value)}/></label><label>{t("Content ends")}<input type="datetime-local" value={ends} onChange={e=>setEnds(e.target.value)}/></label><label>{t("Announcement name")}<input value={name} onChange={e=>setName(e.target.value)}/></label></div><p>{t("Owner copies publish directly. Operator copies require owner approval.")}</p><button type="button" disabled={busy||!mediaId||!name.trim()} onClick={()=>void post({action:"save_announcement",mediaId,name})}>{t("Save reusable announcement")}</button><button className="primary-button" disabled={busy||!mediaId||!selected.length} type="submit">{t("Schedule selected screens")}</button></form>
 {data.operators.length?<form noValidate onSubmit={e=>{e.preventDefault();void post({action:"scope_operator",operatorId,screenIds:selected});}}><h3>{t("Department editor scope")}</h3><label>{t("Department editor")}<select value={operatorId} onChange={e=>setOperatorId(e.target.value)}><option value="">{t("Choose an operator")}</option>{data.operators.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><p>{t("Only selected screens remain accessible. Saving revokes the operator's existing sessions.")}</p><button type="submit" disabled={busy||!operatorId}>{t("Save scope and revoke sessions")}</button></form>:null}
 {error?<p className="form-error" role="alert">{error}</p>:null}<ul aria-live="polite">{results.map((r,i)=><li key={`${r.id}-${i}`}>{r.id}: {t(r.ok?"Succeeded":"Failed")}{r.error?` — ${t(r.error)}`:""}</li>)}</ul>
 <h3>{t("Alert delivery by screen")}</h3><p>{t("Browser render reports do not prove physical panel visibility or official alert delivery.")}</p><div className="fleet-table-scroll"><table><thead><tr>{["Screen","Connection","Received","Applied","Browser rendered","Restored"].map(key=><th key={key}>{t(key)}</th>)}</tr></thead><tbody>{data.alertDelivery.map(r=><tr key={`${r.alert_id}-${r.inventory_id}`}><td>{r.inventory_id}<small>{r.alert_id}</small></td><td>{t(!r.player_id?"Not paired":!r.last_seen_at?"Unknown":Date.now()-Date.parse(r.last_seen_at)>data.staleMs?"Stale / offline":"Online")}</td>{["received_at","applied_at","rendered_at","restored_at"].map(key=><td key={key}>{r[key]?new Date(r[key]).toLocaleString(locale==="fr"?"fr-CA":"en-CA"):t("Not reported")}</td>)}</tr>)}</tbody></table></div>
 <details><summary>{t("Fleet audit history")}</summary><ul>{data.audit.map((a,i)=><li key={i}>{a.created_at} · {a.actor_id} · {a.target_id} · {a.action} · {a.revision??"—"} · {a.priority} · {a.result}</li>)}</ul></details>
 </section>;
}
