import { createHash, randomUUID } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "../../../../lib/auth";
import { getDb } from "../../../../lib/db";
import { organizationIdsForUser } from "../../../../lib/campaigns";
import { isFeatureEnabled } from "../../../../lib/feature-flags";
import { deleteStoredMedia, storeMedia } from "../../../../lib/media-storage";
import { inspectMediaUpload } from "../../../../lib/uploads";
type Context={params:Promise<{id:string}>};

export async function GET(_request:NextRequest,context:Context){const user=await getCurrentUser();if(!user||!["admin","operator","institutional"].includes(user.role))return NextResponse.json({error:"Forbidden"},{status:403});const id=(await context.params).id;const orgs=await organizationIdsForUser(user);const scoped=await getDb().query("SELECT installation_work_orders.id FROM installation_work_orders JOIN placements ON placements.id=installation_work_orders.placement_id JOIN campaigns ON campaigns.id=placements.campaign_id JOIN inventory ON inventory.id=placements.inventory_id WHERE installation_work_orders.id=$1 AND (campaigns.organization_id=ANY($2::text[]) OR inventory.owner_organization_id=ANY($2::text[]))",[id,orgs]);if(!scoped.rows[0])return NextResponse.json({error:"Work order not found"},{status:404});const evidence=await getDb().query("SELECT id,original_name,mime_type,size_bytes,created_at FROM work_order_evidence WHERE work_order_id=$1 ORDER BY created_at",[id]);return NextResponse.json({evidence:evidence.rows});}
export async function POST(request:NextRequest,context:Context){if(!isFeatureEnabled("static_fulfillment"))return NextResponse.json({error:"Not available"},{status:404});const user=await getCurrentUser();if(!user||!["admin","operator","institutional"].includes(user.role))return NextResponse.json({error:"Forbidden"},{status:403});const id=(await context.params).id;const orgs=await organizationIdsForUser(user);const scoped=await getDb().query("SELECT installation_work_orders.id FROM installation_work_orders JOIN placements ON placements.id=installation_work_orders.placement_id JOIN campaigns ON campaigns.id=placements.campaign_id JOIN inventory ON inventory.id=placements.inventory_id WHERE installation_work_orders.id=$1 AND (campaigns.organization_id=ANY($2::text[]) OR inventory.owner_organization_id=ANY($2::text[]))",[id,orgs]);if(!scoped.rows[0])return NextResponse.json({error:"Work order not found"},{status:404});const form=await request.formData();const file=form.get("file");if(!(file instanceof File))return NextResponse.json({error:"Choose a completion photo"},{status:422});const inspected=await inspectMediaUpload(file,["png","jpg"]);if(!inspected||inspected.mediaType!=="image")return NextResponse.json({error:"Completion evidence must be a valid PNG or JPEG image under 50 MB"},{status:422});const evidenceId=`WOE-${randomUUID().replace(/-/g,"").slice(0,12).toUpperCase()}`;const storagePath=await storeMedia(`work-orders/${id}/${evidenceId}.${inspected.extension}`,inspected.bytes,inspected.mimeType);try{await getDb().query("INSERT INTO work_order_evidence (id,work_order_id,original_name,mime_type,size_bytes,storage_path,checksum,uploaded_by,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)",[evidenceId,id,file.name,inspected.mimeType,inspected.bytes.byteLength,storagePath,createHash("sha256").update(inspected.bytes).digest("hex"),user.id,new Date().toISOString()]);return NextResponse.json({id:evidenceId,name:file.name,url:`/api/work-order-evidence/${evidenceId}`},{status:201});}catch{await deleteStoredMedia(storagePath).catch(()=>undefined);return NextResponse.json({error:"Photo could not be saved; retry this file"},{status:500});}}
