import { createHash, randomUUID } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "../../../../lib/auth";
import { getDb, initializeDatabase } from "../../../../lib/db";
import { isFeatureEnabled } from "../../../../lib/feature-flags";
import { organizationIdsForUser } from "../../../../lib/campaigns";
type Context={params:Promise<{id:string}>};

export async function POST(request:NextRequest,context:Context){
 if(!isFeatureEnabled("static_fulfillment"))return NextResponse.json({error:"Not available"},{status:404});
 const user=await getCurrentUser();if(!user||!["admin","operator","institutional"].includes(user.role))return NextResponse.json({error:"Forbidden"},{status:403});
 const key=request.headers.get("idempotency-key");if(!key)return NextResponse.json({error:"Idempotency-Key is required"},{status:422});
 const body=await request.json().catch(()=>({}));const evidenceIds=[...new Set(Array.isArray(body.evidenceIds)?body.evidenceIds.map(String):[])];if(!evidenceIds.length)return NextResponse.json({error:"At least one uploaded completion photo is required"},{status:422});
 await initializeDatabase();const orderId=(await context.params).id;const organizationIds=await organizationIdsForUser(user);const client=await getDb().connect();
 try{await client.query("BEGIN");await client.query("SELECT pg_advisory_xact_lock(hashtext($1))", [`work_order_complete:${user.id}:${key}`]);const requestHash=createHash("sha256").update(JSON.stringify({actorId:user.id,orderId,expectedVersion:body.expectedVersion,evidenceIds,result:body.result,clientShareable:body.clientShareable===true})).digest("hex");const prior=await client.query<{response_body:object;response_status:number;request_hash:string}>("SELECT response_body,response_status,request_hash FROM idempotency_records WHERE scope='work_order_complete' AND idempotency_key=$1",[key]);if(prior.rows[0]){await client.query("ROLLBACK");if(prior.rows[0].request_hash!==requestHash)return NextResponse.json({error:"This request key was already used for different completion data"},{status:409});return NextResponse.json(prior.rows[0].response_body,{status:prior.rows[0].response_status});}
 const order=await client.query<{placement_id:string;version:number;status:string;work_type:string;placement_status:string;production_status:string;organization_id:string}>(`SELECT installation_work_orders.placement_id,installation_work_orders.version,installation_work_orders.status,installation_work_orders.work_type,placements.status placement_status,(SELECT status FROM production_jobs WHERE placement_id=placements.id) production_status,campaigns.organization_id FROM installation_work_orders JOIN placements ON placements.id=installation_work_orders.placement_id JOIN campaigns ON campaigns.id=placements.campaign_id JOIN inventory ON inventory.id=placements.inventory_id WHERE installation_work_orders.id=$1 AND (campaigns.organization_id=ANY($2::text[]) OR inventory.owner_organization_id=ANY($2::text[])) FOR UPDATE OF installation_work_orders`,[orderId,organizationIds]);const current=order.rows[0];if(!current){await client.query("ROLLBACK");return NextResponse.json({error:"Work order not found"},{status:404});}if(current.version!==Number(body.expectedVersion)){await client.query("ROLLBACK");return NextResponse.json({error:"Work order changed; refresh before retrying"},{status:409});}
 if(current.work_type!=="install"||!["ready","scheduled","in_progress"].includes(current.status)||!["confirmed","ready_for_fulfillment"].includes(current.placement_status)||current.production_status!=="delivered"){await client.query("ROLLBACK");return NextResponse.json({error:"Installation requires confirmed terms, delivered production, and a ready work order"},{status:422});}
 const evidence=await client.query<{id:string;original_name:string}>("SELECT id,original_name FROM work_order_evidence WHERE work_order_id=$1 AND id=ANY($2::text[])",[orderId,evidenceIds]);if(evidence.rows.length!==evidenceIds.length){await client.query("ROLLBACK");return NextResponse.json({error:"One or more completion photos are missing; retry those uploads"},{status:422});}
 const now=new Date().toISOString();await client.query("UPDATE placement_issues SET status='resolved',resolved_at=$1 WHERE placement_id=$2 AND status='open'",[now,current.placement_id]);await client.query("UPDATE installation_work_orders SET status='installed',completed_at=$1,result=$2,version=version+1,updated_at=$1 WHERE id=$3",[now,body.result??"completed",orderId]);await client.query("UPDATE placements SET status='live',version=version+1,updated_at=$1 WHERE id=$2",[now,current.placement_id]);const proofId=id("PRF");const retention=new Date(now);retention.setUTCFullYear(retention.getUTCFullYear()+7);const proofEvidence=evidence.rows.map(item=>({id:item.id,name:item.original_name,url:`/api/work-order-evidence/${item.id}`}));await client.query("INSERT INTO proof_records (id,placement_id,work_order_id,proof_type,evidence,client_shareable,public_shareable,certified_by,certified_at,retention_until,created_at) VALUES ($1,$2,$3,'proof_of_posting',$4::jsonb,$5,FALSE,$6,$7,$8,$7)",[proofId,current.placement_id,orderId,JSON.stringify(proofEvidence),body.clientShareable===true,user.id,now,retention.toISOString()]);await client.query("INSERT INTO activity_events (id,organization_id,actor_id,subject_type,subject_id,action,previous_state,next_state,metadata,retention_until,created_at) VALUES ($1,$2,$3,'work_order',$4,'completed',$5,'installed',$6::jsonb,$7,$8)",[id("EVT"),current.organization_id,user.id,orderId,current.status,JSON.stringify({proofId,evidenceCount:evidence.rows.length}),retention.toISOString(),now]);const response={workOrderId:orderId,proofId,status:"installed"};await client.query("INSERT INTO idempotency_records (scope,idempotency_key,request_hash,response_status,response_body,created_at) VALUES ('work_order_complete',$1,$2,200,$3::jsonb,$4)",[key,requestHash,JSON.stringify(response),now]);await client.query("COMMIT");return NextResponse.json(response);
 }catch{await client.query("ROLLBACK").catch(()=>undefined);return NextResponse.json({error:"Completion failed; check server state before retrying"},{status:500});}finally{client.release();}
}
function id(prefix:string){return `${prefix}-${randomUUID().replace(/-/g,"").slice(0,12).toUpperCase()}`;}
